### ISSUE TITLE
ブログを立ち上げた

### ISSUE THREAD

**Issue by yuhr** [yuhr/blog.yuhr.org#1]
このたびブログを立ち上げることにした。筆者のプロフィール表示等はまだ実装していないので、誰なのか知りたければとりあえず[GitHubを見てほしい](https://github.com/yuhr)。また、ここでは今後常体でいこうと思う。他の媒体（Zennなど）で書くときに比べて、あまり読みやすさなどに気を払いすぎて手が止まってしまうことがないよう、つらつらと書き殴っていきたい。

---

あえて今ブログ立ち上げに至ったのは、何の気なしにTwitterを眺めていたら、それとなく機運の高まりを感じたからだ。

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">はてなブログに投稿しました <a href="https://twitter.com/hashtag/%E3%81%AF%E3%81%A6%E3%81%AA%E3%83%96%E3%83%AD%E3%82%B0?src=hash&amp;ref_src=twsrc%5Etfw">#はてなブログ</a><br>言葉だけが最後に残る - 鷲はいまどこを飛ぶか<a href="https://t.co/tpUA1kn48E">https://t.co/tpUA1kn48E</a></p>&mdash; washoe2.2 (@washoe2020) <a href="https://twitter.com/washoe2020/status/1650144629017427969?ref_src=twsrc%5Etfw">April 23, 2023</a></blockquote>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">とても問題意識に共感する（実際自分も「意識的に記述しておかねば各時点の自分が何を考えていたのかは簡単に揮発してしまう」という問題意識から去年自分用のWebサイト↓を立てたので：<br><br>緒言 - gfnweb <a href="https://t.co/7kX5X1wwIw">https://t.co/7kX5X1wwIw</a> ）</p>&mdash; 画力・博士号・油田 (@bd_gfngfn) <a href="https://twitter.com/bd_gfngfn/status/1650147533388419072?ref_src=twsrc%5Etfw">April 23, 2023</a></blockquote>

それぞれのツイートからリンクされている記事をここからもリンクしておく。

- [言葉だけが最後に残る - 鷲はいまどこを飛ぶか](https://washibane.hatenablog.com/entry/2023/04/23/232820)
- [緒言 - gfnweb](https://gfngfn.github.io/ja/posts/2022-05-09-preliminary-remarks/)

---

これらの記事を読んだことは行動のトリガーにすぎず、もともと将来的には何かしらのブログのような媒体を利用したいとは思っていた。執筆媒体という括りでいうと、以前はQiitaを利用していたが、最近では[Zennを利用している](https://zenn.dev/yuhr)。少なくとも今までは、ブログよりはこういった単発記事プラットフォームの方が性に合っていたということなのだろう。しかし、そこでも特に最近はエッセイ記事を書くことが多くなり、これもうさっさとブログこさえた方がいいのでは、と漠然と思いつつ特に行動してはいないという状態だった。

はてなブログにもその他の媒体にも、最後まで食指が動かず、なぜかというとおそらく三日坊主になるのを恐れたのだと思う。これらのBlog as a Serviceとも言うべきマネージドな媒体は、サイトテーマなどを活用して自分好みのブログを作れる感を醸し出しているわりには、とにかく何かしようと思えば自由を制限され、細かい部分を弄れないという事態に直面する経験が繰り返されることで次第に興が削がれていき、どうせその媒体を静かに見捨てることになるのだろう、という先入観がある（これはプロダクトが悪いのではなく単に筆者の性質とのミスマッチの話）。実際、いつだったか、立ち上げて設定を弄くり回しただけでそのまま放置したはてなブログがある。

---

GitHub IssuesをヘッドレスCMSとして使って簡単にブログを立ち上げられるようなソフトウェアがそういえばあったな、と思い出して適当にググってみたところ、r7kamuraさんのブログ記事『[GitHub Issuesでブログを書く](https://r7kamura.com/articles/2022-05-03-github-issues-as-blog)』を見つけた。当人作成の[gialog](https://github.com/r7kamura/gialog)というソフトウェアが紹介されていた。他にも[似たようなソリューション](https://zenn.dev/masaino/articles/aad220db388b5a)が世の中にはたくさん存在するらしかったのでいくつかリポジトリを見てみたりした。

そうしてわかったのは、gialogが最も素晴らしいということだった。 驚くべきことだが、**GitHub上でフォークするだけでブログが立ち上がる**のだ。本当に、文字通り、フォークするだけである。これ以上手順を減らすことはできない。GitHubをすでに日常的に利用しているユーザーが使うブログシステムとしては、間違いなく最高のエルゴノミクスを備えたシステムである。

そんなわけで、今筆者が立ち上げたこのブログは、gialogを以下のリポジトリにフォークして動かしている。

- <https://github.com/yuhr/blog.yuhr.org>

一応、独自ドメインで動かすためには少しソースコードに[変更](https://github.com/yuhr/blog.yuhr.org/compare/7a0199519be7d4790d667fa84872f277b64bdc1d..95a57e7c4aff82ac7ca6e3ad480f70293e902ca4)を加える必要はあった。また、これらの変更を加えた後、独自ドメインでアクセスするとキャッシュの関係でうまくCSSが当たっていないように見えたりもしたが、待つことで解決された。

まったく文句がない。魂がこういうものを求めていたことを実感する。

---

デモサイトの投稿例を見てみると、一つ面白いことに気づく。

- 投稿例: <https://r7kamura.github.io/gialog-example/articles/1>
- 該当するIssue: <https://github.com/r7kamura/gialog-example/issues/1>

Issueの最初の投稿だけでなく、そこに付けたコメントまで含めてコンテンツとしてデプロイされ、できあがったブログ記事の下部に追加表示されている。つまり、本題から逸れるような補足などを後から足すといった、ある意味Twitterのようなマイクロブログと従来の古典的ブログとの中間のような執筆スタイルが可能になる。これは[Zennのスクラップ機能](https://zenn.dev/zenn/articles/about-zenn-scraps)を彷彿とさせる、執筆媒体としては新しめのスタイルだと思う。てっきり、この手の（GitHub IssuesをCMSとして使う類の）ブログシステムは、Issueへのコメントは記事の間違いの指摘とかに使われるものと思っていた。

色々試してみよう。

**Comment by yuhr** [comment]
余談だが、[gfnさんの記事](https://gfngfn.github.io/ja/posts/2022-05-09-preliminary-remarks/)の以下の一節には特に深い共感を覚え、当人への信頼感を強めた。この話題についてはいつかまた別の記事を書くと思う。

> とりわけ昨今（違法といえるかにかかわらず）不道徳なものと看なされる言動が見出された場合は非難が苛烈を極め，ほとんど私刑的に該当者を追放するような動きを共同体が見せることもよくある．たしかに実効性のために或る程度アファーマティヴでなければならないと要請されている側面はあるが，それでも自分は本当に人間が共生する最終的な方法としてそれが望ましいとは思えていない．端的に言えば，“ブラックリストに載った人から順に切り捨てていく” のではなく，どんなに “マヌケ” な思考をしていた人物がいたとしてもその人物が過去を省みた後やはり一員として過ごしていくのだという意識が共有されることが成熟した共同体の姿だと信じたい．

**Comment by yuhr** [comment]
ブログ上で`blockquote`が問題なく表示されるケースと表示されないケースがあるらしい。<s>記事冒頭のツイートの引用は表示されていないが、最後に追加した引用は表示されている。近いうちに修正しなければ。</s>修正した。生のHTMLタグが削られていたようだ。

他にも面白そうなポイントはいろいろある。オーナー以外によるコメントはどう扱うべきか。Issueのクローズ・オープンの機能はどう扱うべきか。そこら辺も実装次第で自分の好きなようにできるというのが嬉しい。

[#1](https://github.com/yuhr/blog.yuhr.org/issues/1)は今後もそういうのを試すための実験場にしようと思う。

**Comment by MintoAoyama** [comment]
（ここは第三者によるコメントです）
